#!/bin/sh


# Define some prompt colors
function __define_echo_ne_colors() {
  # regular colors
  export _K_="\033[0;30m"    # black
  export _R_="\033[0;31m"    # red
  export _G_="\033[0;32m"    # green
  export _Y_="\033[0;33m"    # yellow
  export _B_="\033[0;34m"    # blue
  export _M_="\033[0;35m"    # magenta
  export _C_="\033[0;36m"    # cyan
  export _W_="\033[0;37m"    # white
  # empahsized (bolded) colors
  export _EMK_="\033[1;30m"
  export _EMR_="\033[1;31m"
  export _EMG_="\033[1;32m"
  export _EMY_="\033[1;33m"
  export _EMB_="\033[1;34m"
  export _EMM_="\033[1;35m"
  export _EMC_="\033[1;36m"
  export _EMW_="\033[1;37m"
  # background colors
  export _BGK_="\033[40m"
  export _BGR_="\033[41m"
  export _BGG_="\033[42m"
  export _BGY_="\033[43m"
  export _BGB_="\033[44m"
  export _BGM_="\033[45m"
  export _BGC_="\033[46m"
  export _BGW_="\033[47m"
  # styles
  export _NN_="\033[0m"  # unsets color to term's fg color
  export _EM_="\033[1m"  #bold
  export _DM_="\033[2m"  #dim
  export _UN_="\033[4m"  #underline
  export _BL_="\033[5m"  #blink
  export _RV_="\033[7m"  #reverse
  export _EMQ_="\033[21m" #END bold
  export _DMQ_="\033[22m" #END dim
  export _UNQ_="\033[24m" #END underline
  export _BLQ_="\033[25m" #END blink
  export _RVQ_="\033[27m" #END reverse
  # default user colors
  export _UC_=$_G_                         # user's color
  export _EMUC_=$_EMG_                     # user's bold color
  export _ERRUC_=$_R_                      # user's ERROR color
  export _ERREMUC_=$_EMR_                  # user's bold ERROR color
  # root colors
  [ $UID -eq "0" ] && _UC_=$_R_           # root's color
  [ $UID -eq "0" ] && _EMUC_=$_EMR_       # root's bold color
  [ $UID -eq "0" ] && _ERRUC_=$_K_        # root's ERROR color
  [ $UID -eq "0" ] && _ERREMUC_=$_EMK_    # root's bold ERROR color


}

# Misc GLOBS
pr0="${_G_}SIMONASTIC${_K_}: ${_W_}"  # ok
pr1="${_R_}SIMONASTIC${_K_}: ${_W_}"  # not ok
pr2="${_M_}SIMONASTIC${_K_}: ${_W_}"  # warn
pr3="${_Y_}SIMONASTIC${_K_}: ${_W_}"  # info
prE="${_R_}SIMONASTIC${_K_}: OPERATION ABORTED...${_EMR_}"  # Abort message

wl1="${_EMK_}${_UN_}                                                               ${_NN_}"

welcome="\n
 ____  _                             ____  _   _      _\n
/ ___|(_)_ __ ___   ___  _ __   __ _/ ___|| |_(_) ___| | __\n
\___ \| | '_ \` _ \\/  _ \\| '_ \ / _\` \___ \| __| |/ __| |/ /\n
 ___) | | | | | | | (_) | | | | (_| |___) | |_| | (__|   <\n
|____/|_|_| |_| |_|\___/|_| |_|\__,_|____/ \__|_|\___|_|\_\\ \n
\n
"

intro="
\n
\n  This is the Macos version of Sim on a Stick, an easy to use,
\n  preconfigured OpenSim server with no installation. Lauch it
\n  from your USB stick, hard drive, anywhere. Based on the 'Diva'
\n  distribution of OpenSim, which makes bundling a breeze :)
\n
\n  CREDITS :
\n  - Ener Hax    : original idea, windows version
\n  - Pete Atolia : Macos version
\n
"


# Help
function usage(){
  echo -ne "
  ${_M_}SimonaStick for Macos${_W_}

  USAGE : ${_G_}simonastic ${_EMG_}start
          ${_R_}simonastic ${_EMR_}stop${_W_}

"
}


